kind: Simple
apiVersion: k3d.io/v1alpha2
name: my-cluster
image: rancher/k3s:latest
servers: 1
agents: 3
ports:
- port: 8080:80
  nodeFilters:
  - loadbalancer
# options:
#   k3s:
#     extraServerArgs:
#     - --no-deploy=traefik
